version: "3.1"
services:
  web:
    restart: always
    image: "happygick/act3compnubeme:latest"
    build: .
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USER: "grupo8"
      POSTGRES_DB: "dbgrupo8"
      POSTGRES_HOST: "db"
      APP_PORT: "8000"
    ports:
      - "8000:8000"
    networks:
      - meluardo_net
    depends_on:
      - db
  db:
    env_file:
      - .env
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USER: "grupo8"
      POSTGRES_DB: "dbgrupo8"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - meluardo_net

volumes:
  pg_data:
    driver: local
    driver_opts:
      o: "addr=nfs01,rw"
      type: "nfs"
      device: ":/data/docker-vols/grupo8/pgdata"

networks:
  meluardo_net:
    driver: overlay
