version: "3.1"
services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    networks:
      - meluardo_net
    depends_on:
      - db
  db:
    env_file:
      - .env
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    networks:
      - meluardo_net

networks:
  meluardo_net:
