version: "3.1"
services:
  web:
    restart: always
    image: 127.0.0.1:5000/act3compnubeme
    build: .
    ports:
      - "8000:8000"
    networks:
      - meluardo_net
    depends_on:
      - db
  db:
    env_file:
      - .env
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - meluardo_net

volumes:
  pg_data:
    driver: local
    driver_opts:

networks:
  meluardo_net:
    driver: overlay
